[tools]
go = "latest"
node = "latest"
python = "latest"
direnv = "latest"
rust = "latest"
ruby = "latest"
pnpm = "latest"
biome = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "go", "node"]
color = true
